### ISSUE TITLE
Emmmm那个install_CentOS脚本有一部装了一个神奇东西导致我所有yum全报错

### ISSUE THREAD

**Issue by RoyZ-iwnl** [v2ray/v2ray-Panel#5]
`--2018-02-28 21:14:36--  http://people.centos.org/tru/devtools-2/devtools-2.repo
Resolving people.centos.org (people.centos.org)... 50.28.24.115
Connecting to people.centos.org (people.centos.org)|50.28.24.115|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://people.centos.org/tru/devtools-2/devtools-2.repo [following]
--2018-02-28 21:14:37--  https://people.centos.org/tru/devtools-2/devtools-2.repo
Connecting to people.centos.org (people.centos.org)|50.28.24.115|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 175
Saving to: ‘/etc/yum.repos.d/devtools-2.repo’`

devtools-2，就是他，小白不太懂，但是这应该是给我装了一个yum源？
装了他之后我所有的yum行为都会被报错
`Loaded plugins: fastestmirror
http://people.centos.org/tru/devtools-2/7/x86_64/RPMS/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

 One of the configured repositories failed (testing 2 devtools for CentOS 7),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=testing-devtools-2-centos-7 ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable testing-devtools-2-centos-7
        or
            subscription-manager repos --disable=testing-devtools-2-centos-7

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=testing-devtools-2-centos-7.skip_if_unavailable=true

failure: repodata/repomd.xml from testing-devtools-2-centos-7: [Errno 256] No more mirrors to try.
http://people.centos.org/tru/devtools-2/7/x86_64/RPMS/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
`

**Comment by RoyZ-iwnl** [comment]
删除/etc/yum.repos.d下的devtools-2.repo就恢复了
补充下环境:阿里云国际香港 CentOS 7.4 64,除了把ECS监控卸载，阿里云服务卸载其他没动。

**Comment by Bethannfrum** [comment]
Fix and restore it to the original form and release old documents

**Comment by kslr** [comment]
不好意思，目前应该处于不可用状态。

近期正在考虑用简单语言和新API重构的计划，就不需要影响操作系统了。

**Comment by kslr** [comment]
@losfair 你还在使用if***.com的邮箱吗，我向你发送了一封邮件，可以收到吗？
