### ISSUE TITLE
如何获取node key

### ISSUE THREAD

**Issue by ghost** [v2ray/v2ray-Panel#6]
使用的master分支，50a00468
master（panel）运行正常，node，填写admin的UUID，报错，invalid key
如何获取node key

**Comment by ghost** [comment]
不太理解，承载节点初始化所需的 Node Key 是 Panel 中创建节点时生成的。

**Comment by losfair** [comment]
先登录 Master Panel 创建节点，然后可以看到分配给该节点的 Key .

把这个 Key 填入节点端即可.

**Comment by ghost** [comment]
不知道有没有理解错。
使用的是默认端口，运行master后，登录,ip:1247(这个是master-panel吧。)


![_2018-03-28_22-46-22](https://user-images.githubusercontent.com/13147785/38036702-ddf1f7b0-32d9-11e8-8c00-82c5f8e40538.png)


    "mode": "node", 
    "listen_addr": "127.0.0.1:5212", 
    "db_url": "mongodb://127.0.0.1:27017/v2ray-panel-node", 
    "master_url": "http://127.0.0.1:1247", 
    "node_key": "25e30718-dcb5-44d1-8fb1-cf57d74155ab", 
    "binary_path": "/usr/local/v2ray-panel/v2ray_patched", 


填入该ID后依然是invalid key


v2ray_patched: no process found
Created temporary config.json: /tmp/tmp-4361M1FsMiGy67r6/config.json
V2Ray 2.34 (One for all) Custom
An unified platform for anti-censorship.
Sending 0 events
Wed Mar 28 14:49:52 2018 [INFO] IceServer::listen_in_this_thread: Ice Server v0.2.0 listening at 127.0.0.1:5212
Invalid key
2018/03/28 14:49:52 [Debug]App|Proxyman|Inbound: creating tcp worker on 0.0.0.0:10001
2018/03/28 14:49:52 [Info]Transport|Internet|TCP: listening TCP on 0.0.0.0:10001
2018/03/28 14:49:52 [Warning]Core: V2Ray started

**Comment by losfair** [comment]
请访问 `/admin/index` 进入管理员控制面板，在其中可以创建节点并拿到 Key .

**Comment by losfair** [comment]
用户 ID 不是节点 Key

**Comment by ghost** [comment]
Node_key已经解决。访问IP:port/admin/index
添加新用户/重置Vmess ID后，/etc/node.json中未出现相关的Vmess ID，如何在node.json里关联/同步用户重置的Vmess ID呢？

**Comment by Bethannfrum** [comment]
Fix and restore to original form and release old documents
